process_observables: ['jet_axis']
jetR: [0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
debug_level: 0
dry_run: False
fast_simulation: False
use_ev_id_ext: True
  
# Observable block
jet_axis:

  common_settings:
    xtitle: '#it{#DeltaR}_{axis}'
    ytitle: '#frac{1}{#it{N}_{jets}} #frac{d#it{N}}{d#DeltaR_{axis}}'
    pt_bins_reported: [20, 40]
    plot_overlay_list:
      - ['config1', 'config14', 'config15', 'config16', 'config17']
      - ['config1', 'config15', 'config19', 'config23']
    #max_reg_param: 3

  config1:
    axis: 'Standard_WTA'
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 40, 50, 60, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 40, 50, 60, 80, 100, 135]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4] 
    obs_max_reported: [0.2]
    obs_bins_det: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_bins_det_sys_binning: [0.,0.01,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.055,0.06,0.065,0.07,0.075,0.08,0.121,0.2,0.4]
    reg_param:
      0.2: 3
      0.4: 3
      
  config14:
    axis: 'WTA_SD_1'
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 40, 50, 60, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 40, 50, 60, 80, 100, 135]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_max_reported: [0.2]
    obs_bins_det: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_bins_det_sys_binning: [0.,0.01,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.055,0.06,0.065,0.07,0.075,0.08,0.121,0.2,0.4]
    reg_param:
      0.2: 3
      0.4: 3

  config15:
    axis: 'WTA_SD_2'
    SoftDrop:
      zcut: 0.1
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 40, 50, 60, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 40, 50, 60, 80, 100, 135]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_max_reported: [0.2]
    obs_bins_det: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_bins_det_sys_binning: [0.,0.01,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.055,0.06,0.065,0.07,0.075,0.08,0.121,0.2,0.4]
    reg_param:
      0.2: 3
      0.4: 3

  config16:
    axis: 'WTA_SD_3'
    SoftDrop:
      zcut: 0.1
      beta: 2
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 40, 50, 60, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 40, 50, 60, 80, 100, 135]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_max_reported: [0.2]
    obs_bins_det: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_bins_det_sys_binning: [0.,0.01,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.055,0.06,0.065,0.07,0.075,0.08,0.121,0.2,0.4]
    reg_param:
      0.2: 3
      0.4: 3

  config17:
    axis: 'WTA_SD_4'
    SoftDrop:
      zcut: 0.1
      beta: 3
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 40, 50, 60, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 40, 50, 60, 80, 100, 135]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_max_reported: [0.2]
    obs_bins_det: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_bins_det_sys_binning: [0.,0.01,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.055,0.06,0.065,0.07,0.075,0.08,0.121,0.2,0.4]
    reg_param:
      0.2: 3
      0.4: 3

  config19:
    axis: 'WTA_SD_6'
    SoftDrop:
      zcut: 0.2
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 40, 50, 60, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 40, 50, 60, 80, 100, 135]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_max_reported: [0.2]
    obs_bins_det: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_bins_det_sys_binning: [0.,0.01,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.055,0.06,0.065,0.07,0.075,0.08,0.121,0.2,0.4]
    reg_param:
      0.2: 3
      0.4: 3

  config23:
    axis: 'WTA_SD_10'
    SoftDrop:
      zcut: 0.3
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 40, 50, 60, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 40, 50, 60, 80, 100, 135]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_max_reported: [0.2]
    obs_bins_det: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.1, 0.121, 0.15, 0.2, 0.4]
    obs_bins_det_sys_binning: [0.,0.01,0.02,0.025,0.03,0.035,0.04,0.045,0.05,0.055,0.06,0.065,0.07,0.075,0.08,0.121,0.2,0.4]
    reg_param:
      0.2: 3
      0.4: 3

###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/rstorage/alice/AnalysisResults/rey/'
roounfold_path: '/home/rey/RooUnfold/RooUnfold/libRooUnfold.so'

analysis_observable: 'jet_axis'
do_unfolding: True
force_rebin: False
do_systematics: True
do_plot_final_result: True
do_plot_performance: True
figure_approval_status: 'Work in Progress'

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - fastsim_generator0
  - fastsim_generator1

fastsim_syst_fit: False

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/rey/313695/AnalysisResultsFinal.root'
main_response: '/rstorage/alice/AnalysisResults/rey/313696/AnalysisResultsFinal.root'
trkeff_response: '/rstorage/alice/AnalysisResults/rey/313697/AnalysisResultsFinal.root'
fastsim_response: ['/rstorage/alice/AnalysisResults/rey/317281/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/rey/317442/AnalysisResultsFinal.root']
# Prior variation parameters
prior_variation_option: 4
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
