process_observables: ['jet_axis']
jetR: [0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
debug_level: 0
dry_run: False
fast_simulation: False
use_ev_id_ext: True
  
# Observable block
jet_axis:

  common_settings:
    xtitle: '#it{#DeltaR}_{axis}'
    ytitle: '#frac{1}{#it{N}} #frac{d#it{N}}{d#it{#DeltaR}_{axis}}'
    pt_bins_reported: [40, 60]
    plot_overlay_list:
      - ['config2' , 'config3' , 'config4' , 'config5' ]
      - ['config11' , 'config7' , 'config3']
    #max_reg_param: 3

  config11:
    axis: 'Standard_SD_10'
    SoftDrop:
      zcut: 0.3
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 30, 40, 60, 70, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 30, 40, 60, 70, 80, 100, 135]
    obs_bins_truth: [0,0.005,0.01,0.015,0.02,0.025,0.03,0.035,0.04,0.05,0.072,0.1]
    obs_max_reported: [0.072]
    obs_bins_det: [0,0.005,0.01,0.015,0.02,0.025,0.03,0.035,0.04,0.05,0.072,0.1]
    obs_bins_det_sys_binning: [0,0.005,0.009,0.013,0.018,0.024,0.031,0.036,0.041,0.046,0.05,0.055,0.06,0.065,0.07,0.075,0.1]
    reg_param: 
      0.4: 3

  config7:
    axis: 'Standard_SD_6'
    SoftDrop:
      zcut: 0.2
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 30, 40, 60, 70, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 30, 40, 60, 70, 80, 100, 135]
    obs_bins_truth: [0., 0.002, 0.006, 0.01,0.014,0.018,0.020,0.024,0.0285,0.035,0.05,0.08]
    obs_max_reported: [0.05]
    obs_bins_det: [0., 0.002, 0.006, 0.01,0.014,0.018,0.020,0.024,0.0285,0.035,0.05,0.08]
    obs_bins_det_sys_binning: [0., 0.002, 0.005, 0.009,0.013,0.016,0.019,0.025,0.029,0.037,0.045,0.055,0.08]
    reg_param: 
      0.4: 3

  config2:
    axis: 'Standard_SD_1'
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 30, 40, 60, 70, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 30, 40, 60, 70, 80, 100, 135]
    obs_bins_truth: [0.,0.002,0.005,0.0075,0.01,0.0125,0.015,0.0175,0.0225,0.0275,0.035,0.05]
    obs_max_reported: [0.035]
    obs_bins_det: [0.,0.002,0.005,0.0075,0.01,0.0125,0.015,0.0175,0.0225,0.0275,0.035,0.05]
    obs_bins_det_sys_binning: [0.,0.002,0.0055,0.007,0.011,0.013,0.016,0.018,0.021,0.023,0.027,0.03,0.035,0.05]
    reg_param: 
      0.4: 3

  config3:
    axis: 'Standard_SD_2'
    SoftDrop:
      zcut: 0.1
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 30, 40, 60, 70, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 30, 40, 60, 70, 80, 100, 135]
    obs_bins_truth: [0.,0.002,0.005,0.0075,0.01,0.0125,0.015,0.0175,0.0225,0.0275,0.035,0.05]
    obs_max_reported: [0.035]
    obs_bins_det: [0.,0.002,0.005,0.0075,0.01,0.0125,0.015,0.0175,0.0225,0.0275,0.035,0.05]
    obs_bins_det_sys_binning: [0.,0.002,0.0055,0.007,0.011,0.013,0.016,0.018,0.021,0.023,0.027,0.03,0.035,0.05]
    reg_param: 
      0.4: 3

  config4:
    axis: 'Standard_SD_3'
    SoftDrop:
      zcut: 0.1
      beta: 2
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 30, 40, 60, 70, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 30, 40, 60, 70, 80, 100, 135]
    obs_bins_truth: [0.,0.002,0.005,0.0075,0.01,0.0125,0.015,0.0175,0.0225,0.0275,0.035,0.05]
    obs_max_reported: [0.035]
    obs_bins_det: [0.,0.002,0.005,0.0075,0.01,0.0125,0.015,0.0175,0.0225,0.0275,0.035,0.05]
    obs_bins_det_sys_binning: [0.,0.002,0.0055,0.007,0.011,0.013,0.016,0.018,0.021,0.023,0.027,0.03,0.035,0.05]
    reg_param: 
      0.4: 3

  config5:
    axis: 'Standard_SD_4'
    SoftDrop:
      zcut: 0.1
      beta: 3
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 30, 40, 60, 70, 80, 100, 130]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 30, 40, 60, 70, 80, 100, 135]
    obs_bins_truth: [0.,0.002,0.005,0.0075,0.01,0.0125,0.015,0.0175,0.0225,0.0275,0.035,0.05]
    obs_max_reported: [0.035]
    obs_bins_det: [0.,0.002,0.005,0.0075,0.01,0.0125,0.015,0.0175,0.0225,0.0275,0.035,0.05]
    obs_bins_det_sys_binning: [0.,0.002,0.0055,0.007,0.011,0.013,0.016,0.018,0.021,0.023,0.027,0.03,0.035,0.05]
    reg_param: 
      0.4: 3

###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/rstorage/alice/AnalysisResults/rey/'
roounfold_path: '/home/rey/RooUnfold/RooUnfold/libRooUnfold.so'

analysis_observable: 'jet_axis'
do_unfolding: True
force_rebin: False
do_systematics: True
do_plot_final_result: True
do_plot_performance: True
figure_approval_status: 'Preliminary'

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - fastsim_generator0
  - fastsim_generator1

fastsim_syst_fit: False

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/rey/471916/AnalysisResultsFinal.root'
main_response: '/rstorage/alice/AnalysisResults/rey/472075/AnalysisResultsFinal.root'
trkeff_response: '/rstorage/alice/AnalysisResults/rey/473832/AnalysisResultsFinal.root'
fastsim_response: ['/rstorage/alice/AnalysisResults/rey/472800/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/rey/472801/AnalysisResultsFinal.root']
# Prior variation parameters
prior_variation_option: 4
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
