# Processing parameters
jetR: [0.2,0.4]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['jet_axis']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0

# Observable block
jet_axis:
  config1:
    axis: 'Standard_WTA'

  config2:
    axis: 'Standard_SD_1'
    SoftDrop:
      zcut: 0.1
      beta: 0

  config3:
    axis: 'Standard_SD_2'
    SoftDrop:
      zcut: 0.1
      beta: 1

  config4:
    axis: 'Standard_SD_3'
    SoftDrop:
      zcut: 0.1
      beta: 2

  config5:
    axis: 'Standard_SD_4'
    SoftDrop:
      zcut: 0.1
      beta: 3

  config6:
    axis: 'Standard_SD_6'
    SoftDrop:
      zcut: 0.2
      beta: 1

  config7:
    axis: 'Standard_SD_10'
    SoftDrop:
      zcut: 0.3
      beta: 1

  config8:
    axis: 'WTA_SD_1'
    SoftDrop:
      zcut: 0.1
      beta: 0

  config9:
    axis: 'WTA_SD_2'
    SoftDrop:
      zcut: 0.1
      beta: 1

  config10:
    axis: 'WTA_SD_3'
    SoftDrop:
      zcut: 0.1
      beta: 2

  config11:
    axis: 'WTA_SD_4'
    SoftDrop:
      zcut: 0.1
      beta: 3

  config12:
    axis: 'WTA_SD_6'
    SoftDrop:
      zcut: 0.2
      beta: 1

  config13:
    axis: 'WTA_SD_10'
    SoftDrop:
      zcut: 0.3
      beta: 1
