# Processing parameters
jetR: [0.4]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['jet_axis']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0

# Observable block
jet_axis:
  config1:
    axis: 'Standard_WTA'

  config2:
    axis: 'Standard_SD_1'
    SoftDrop:
      zcut: 0.1
      beta: 0

  config3:
    axis: 'WTA_SD_1'
    SoftDrop:
      zcut: 0.1
      beta: 0
