process_observables: ['jet_axis']
jetR: [0.2,0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.04
debug_level: 0
dry_run: False
fast_simulation: False
use_ev_id_ext: True
  
# Observable block
jet_axis:
  config1:
    axis: 'Standard_WTA'
    
  config2:
    axis: 'Standard_SD_1'
    SoftDrop:
      zcut: 0.1
      beta: 0
    
  config3:
    axis: 'Standard_SD_2'
    SoftDrop:
      zcut: 0.1
      beta: 1
    
  config4:
    axis: 'Standard_SD_3'
    SoftDrop:
      zcut: 0.1
      beta: 2

  config5:
    axis: 'Standard_SD_4'
    SoftDrop:
      zcut: 0.1
      beta: 3      

  config7:
    axis: 'Standard_SD_6'
    SoftDrop:
      zcut: 0.2
      beta: 1

  config11:
    axis: 'Standard_SD_10'
    SoftDrop:
      zcut: 0.3
      beta: 1

  config14:
    axis: 'WTA_SD_1'
    SoftDrop:
      zcut: 0.1
      beta: 0

  config15:
    axis: 'WTA_SD_2'
    SoftDrop:
      zcut: 0.1
      beta: 1

  config16:
    axis: 'WTA_SD_3'
    SoftDrop:
      zcut: 0.1
      beta: 2

  config17:
    axis: 'WTA_SD_4'
    SoftDrop:
      zcut: 0.1
      beta: 3

  config19:
    axis: 'WTA_SD_6'
    SoftDrop:
      zcut: 0.2
      beta: 1

  config23:
    axis: 'WTA_SD_10'
    SoftDrop:
      zcut: 0.3
      beta: 1
