# Configuration for:
#   (a) Processing of ROOT trees into histograms
#   (b) Analysis of histograms into final result
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single unfolded result.
# One can also specify a list of jetR, which will be looped over.
#
# The process step is intended  to loop over all observables simultaneously
# The analysis step is intended to run for a single observable block

process_observables: ['energy_drop']
jetR: [0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
debug_level: 0
dry_run: False
fast_simulation: False
use_ev_id_ext: True
  
# Observable block
energy_drop:

  common_settings:
    xtitle: 'ED #equiv (p^{ch}_{T}-p^{ch}_{T,gr})/p^{ch}_{T}'
    ytitle: '#frac{1}{#it{N}_{jets}} #frac{d#it{N}}{dED}'
    pt_bins_reported: [20, 40, 60, 80]
    plot_overlay_list:
      - ['config1', 'config2']

  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.1, 0.2] # 0.001
    obs_bins_det: [0., 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.1, 0.2, 0.3, 0.4] # 0.001
    obs_bins_det_sys_binning: [0., 0.006, 0.011, 0.016, 0.021, 0.026, 0.032, 0.04, 0.048, 0.06, 0.1, 0.2, 0.3, 0.4]
    reg_param:
      0.4: 3

  config2:
    SoftDrop:
      zcut: 0.1
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.1, 0.2] # 0.001
    obs_bins_det: [0., 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.06, 0.1, 0.2, 0.3, 0.4] # 0.001
    obs_bins_det_sys_binning: [0., 0.006, 0.011, 0.016, 0.021, 0.026, 0.032, 0.04, 0.048, 0.06, 0.1, 0.2, 0.3, 0.4]
    reg_param:
      0.4: 3

###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/rstorage/alice/AnalysisResults/rey/'
roounfold_path: '/home/rey/RooUnfold/RooUnfold/libRooUnfold.so'

analysis_observable: 'energy_drop'
do_unfolding: True
force_rebin: False
do_systematics: True
do_plot_final_result: False
do_plot_performance: True
figure_approval_status: 'Work in Progress'

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning]
systematics_list:
  - main
#  - trkeff
#  - prior1
#  - prior2
#  - truncation
#  - binning

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/rey/191517/LHC17pq/448/20-06-2020/448_20200619-0610/unmerged/combined.root'
main_response: '/rstorage/alice/AnalysisResults/rey/191619/LHC18b8/449/combined.root'
trkeff_response: '/rstorage/alice/AnalysisResults/rey/191619/LHC18b8/449/combined.root'

# Prior variation parameters
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
